# Generated by Django 4.2.5 on 2024-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njsmti_app', '0002_allfaculty_contact_diary_faculty_material_query_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='njsmticampus@gmail.com', max_length=80)),
                ('password', models.CharField(default='director@12', max_length=24)),
            ],
        ),
    ]
