# Generated by Django 4.2.5 on 2024-10-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njsmti_app', '0005_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents_mob',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_mob',
            field=models.CharField(max_length=15),
        ),
    ]
