# Generated by Django 4.2.5 on 2024-10-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njsmti_app', '0007_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=29),
        ),
    ]
