# Generated by Django 4.2.5 on 2024-10-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njsmti_app', '0008_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyquery',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
